---
functional:
  - Сайт должен иметь форму регистрации 
  - Сайт должен иметь возможность пригласить друзей в игру
  - Сайт должен формировать рейтинг пользователей по количеству набранных очков
  - Сайт должен иметь форму авторизации
  - Сайт должен иметь возможность авторизации через сторонние сервисы
  - Сайт должен иметь возможность создать игру с ботом
  - Сайт должен предоставить возможность выбора разных языков программирования
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен работать по протоколу https
  - Сайт должен успешно авторизовать зарегистрированного пользователя
  - Сайт должен иметь возможность восстановления пароля
  - Нельзя зарегистрировать нового пользователя если логин уже существует
  - Данные пользователей должны быть защищены от несанкционированного доступа
